#%RAML 1.0 NamedExample
Empdata:

- id: 1
  Name: chris
  Email: chris@gmail.com
  Age: 20
  City: Bangalore
  Project: ABC
  Manager: Steve
- id: 2
  Name: ram
  Email: ram@gmail.com
  Age: 21
  City: Delhi
  Project: xyz
  Manager: Steve
- id: 3
  Name: steve
  Email: steve@gmail.com
  Age: 25
  City: Mumbai
  Project: sss
  Manager: Bell




  